### ISSUE TITLE
why true_score/fake_score have not T as input?  only have image/latent and label?

### ISSUE THREAD

**Issue by Stick-To** [mingyuanzhou/SiD#2]

**Comment by mingyuanzhou** [comment]
The EDM network takes sigma_t instead of t as its input. They are one-to-one mapped to each other, which means if we know t, we know sigma, and if we know sigma, we also know t. 

y_real = true_score(y + n, sigma, labels, augment_labels=augment_labels)
y_fake = fake_score(y + n, sigma, labels, augment_labels=augment_labels)
